### ISSUE TITLE
[Question] What do the current_instance.json and instances.json files located in $HOME/.config/pipe-viewer mean?

### ISSUE THREAD

**Issue by soonan5** [trizen/pipe-viewer#150]
After upgrading pipe-viewer to `0.4.4` I have noticed the existence of these files (which never happened with `0.4.3`). What exactly do they do?
![4](https://user-images.githubusercontent.com/109312533/205190721-b390c57d-4ca3-40e4-a439-ca429036b343.png)

**Comment by trizen** [comment]
- "instances.json" is a list of Invidious instances from https://api.invidious.io/
- "current_instance.json" is the selected invidious instance by pipe-viewer that is used across multiple sessions

The above applies only when the "api_host" config-option is set to "auto". To use a specific invidious instance, change the value of  " api_host" to something like `api_host => "invidious.snopyta.org", `.

The invidious instances are used as a fallback method when our code fails (or when `prefer_invidious` is set to 1). They are also by default for retrieving YouTube comments and for retrieving videos from a specific category.

I hope this answers your question. Additionally, feel free to take a look at the source-code as well, in order to see what really happens under the hood.

**Comment by soonan5** [comment]
Thank you for your explanation. Sure! I will take a look at the code; I just didn't know exactly what its function was. Don't worry, it's solved. Thanks again.
