### ISSUE TITLE
TITLE token is broken when using umpv

### ISSUE THREAD

**Issue by sun95n** [trizen/pipe-viewer#156]
Hi. I finally figured out [how to integrate the umpv script](https://github.com/mpv-player/mpv/issues/11043) into pipe-viewer. However, I ran into a problem: **The special token `*TITLE*` is broken.** I suspect that it is the arg syntax because in `--force-media-title=` there must be a container: `''` however this already exists in `env MPV='...'` So there could be a conflict between the two. I forgot to mention that you need to set `split_videos` to `0` to get audio.

```
  video_player_selected       => "mpv",
  video_players               => {
                                   mpv => {
                                            arg   => "*VIDEO*",
                                            audio => "--audio-file=*AUDIO*",
                                            cmd   => "env MPV='mpv --really-quiet --force-media-title=*TITLE* --no-ytdl' umpv",
                                            fs    => "--fullscreen",
                                            srt   => "--sub-file=*SUB*",
                                          },
```
![02](https://user-images.githubusercontent.com/120290802/210188088-b1c3c358-cecb-4b3e-a497-89c3527f1300.png)
![01](https://user-images.githubusercontent.com/120290802/210188091-583bddec-8537-4481-a505-c575336c6be8.jpg)

**Comment by trizen** [comment]
Try to use double quotes:

```
cmd   => "env MPV=\"mpv --really-quiet --force-media-title=*TITLE* --no-ytdl\" umpv",
```

**Comment by trizen** [comment]
After looking at the source code of `umpv`, we can see where the issue is:

```python
opts = (os.getenv("MPV") or "mpv").split()
```

`umpv` simply splits the value of `$MPV` by whitespace, without taking into account any quotation marks, which is wrong.

A workaround would be to replace whitespace characters in the `*TITLE*`, with some other character, like `-`:

```perl
cmd   => "TITLE=\$(perl -E 'say\$ARGV[0]=~s/\\\s/-/gr' *TITLE*); env MPV=\"mpv --really-quiet --force-media-title=\$TITLE --no-ytdl\" umpv",
```

**Comment by trizen** [comment]
I can reproduce the issue outside of `pipe-viewer` as well:

```console
env MPV="mpv --force-media-title=name1" umpv 1.mp4
env MPV="mpv --force-media-title=name2" umpv 2.mp4
```

The title will keep the name `name1` while playing `2.mp4` as well.

That's because the `$MPV` option is read by [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv#L81) only when creating the socket when it doesn't already exist.
