### ISSUE TITLE
switch to yt-dlp?

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#38]
yt-dlp is a fork of youtube-dl
https://github.com/yt-dlp/yt-dlp

youtube-dl didn't have a release for 2 months now.... you even manually added support for age restricted videos. 
You might want to consider officially switching to yt-dlp, it seams to be the best of youtube-dl forks. (it even has "--write-comments")

now i also notice that you don't mention youtube-dl in the dependencies.

**Comment by Dynexyst** [comment]
You can change the ytdl binary mpv uses (either as an argument or a mpv.conf option)
--script-opts=ytdl_hook-ytdl_path=yt-dlp

**Comment by trizen** [comment]
It's also possible to change the value of `ytdl_cmd` in the config file of pipe-viewer.

But preferring `yt-dlp` (when available) over `youtube-dl` seems like a good thing.

`youtube-dl` is not listed as a dependecy because `pipe-viewer` works perfectly fine without it, using invidious to extract video info when our code fails.

**Comment by pirate486743186** [comment]
You misunderstood, I wasn't asking a question.  I was just saying that youtube-dl has no pulse. I was saying that pipe-viewer should probably switch to yt-dlp.
