### ISSUE TITLE
Weird version mismatch error

### ISSUE THREAD

**Issue by Dynexyst** [trizen/pipe-viewer#60]
Hey, suddenly (probably due to a system update), my pipe-viewer install stopped working (doesn't open). It works on my other PC also running up-to-date arch. Reinstall does not help. Running from source works fine (but id rather have my aur manager update this instead of doing it manually.)

Here is the error:
WWW::PipeViewer version v0.1.8 required--this is only version v0.1.7 at /usr/bin/pipe-viewer line 49.
BEGIN failed--compilation aborted at /usr/bin/pipe-viewer line 49.

(After uninstall i verified /usr/bin/pipe-viewer is gone too)

**Comment by trizen** [comment]
This happens if `pipe-viewer` was installed manually before, then installed and updated using the package manager, without removing the manually installed version.

The manually installed version, by default, gets installed in `/usr/share/perl5/site_perl/`, while the package manager version gets installed in `/usr/share/perl5/vendor_perl/`. However, the `site_perl` directory takes precedence over `vendor_perl`.

To check if this is the case, run the following command:

```
perl -MWWW::PipeViewer -E 'say $INC{"WWW/PipeViewer.pm"}'
```

If the output is `/usr/share/perl5/site_perl/WWW/PipeViewer.pm`, then run the following commands:

```
sudo rm /usr/share/perl5/site_perl/WWW/PipeViewer.pm
sudo rm -r /usr/share/perl5/site_perl/WWW/PipeViewer
```
